import type { IncidentServerType } from './IncidentsService';

export const INCIDENTS: IncidentServerType[] = [
  {
    id: 'INC-1001',
    title: 'Рост 5xx ошибок в API оформления',
    service: 'Оформление',
    priority: 'critical',
    status: 'in-progress',
    updatedAt: '2026-09-13T16:40:00.000Z',
    assignee: 'Vip Admin',
    description:
      'При создании заказа API оформления отвечает 5xx. Пользователи не могут завершить покупку.',
  },
  {
    id: 'INC-1002',
    title: 'Таймауты при оплате банковскими картами',
    service: 'Платежи',
    priority: 'high',
    status: 'investigating',
    updatedAt: '2026-09-13T15:55:00.000Z',
    assignee: 'Иван Кузнецов',
    description:
      'Часть платежей по картам завершается по таймауту. Клиенты видят ошибку и повторяют оплату.',
  },
  {
    id: 'INC-1003',
    title: 'Недоступность личного кабинета пользователей',
    service: 'Аккаунты',
    priority: 'critical',
    status: 'in-progress',
    updatedAt: '2026-09-13T14:20:00.000Z',
    assignee: 'Vip Admin',
    description:
      'Личный кабинет недоступен для части пользователей. Страница профиля открывается с ошибкой.',
  },
  {
    id: 'INC-1004',
    title: 'Задержка доставки уведомлений в мобильном приложении',
    service: 'Уведомления',
    priority: 'medium',
    status: 'monitoring',
    updatedAt: '2026-09-13T13:05:00.000Z',
    assignee: 'Пётр Волков',
    description: 'Push-уведомления доставляются с задержкой до нескольких минут после события.',
  },
  {
    id: 'INC-1005',
    title: 'Ошибки авторизации через SSO',
    service: 'Аутентификация',
    priority: 'high',
    status: 'in-progress',
    updatedAt: '2026-09-13T12:42:00.000Z',
    assignee: 'Елена Новикова',
    description:
      'При входе через SSO пользователи получают ошибку авторизации и не могут попасть в систему.',
  },
  {
    id: 'INC-1006',
    title: 'Повышенная latency в поиске по каталогу',
    service: 'Поиск',
    priority: 'medium',
    status: 'investigating',
    updatedAt: '2026-09-13T11:18:00.000Z',
    assignee: 'Иван Кузнецов',
    description:
      'Операторы видят старые версии полисов в выдаче, пока вручную не обновят страницу.',
  },
  {
    id: 'INC-1007',
    title: 'Сбой синхронизации остатков на складе',
    service: 'Склад',
    priority: 'high',
    status: 'in-progress',
    updatedAt: '2026-09-13T10:30:00.000Z',
    assignee: 'Сергей Морозов',
    description:
      'Остатки товаров на складе не синхронизируются. В каталоге отображаются неактуальные данные.',
  },
  {
    id: 'INC-1008',
    title: 'Некорректный расчёт скидок в корзине',
    service: 'Корзина',
    priority: 'low',
    status: 'new',
    updatedAt: '2026-09-12T19:10:00.000Z',
    assignee: 'Ольга Белова',
    description: 'Для части промокодов итоговая сумма в корзине считается неверно.',
  },
  {
    id: 'INC-1009',
    title: 'Частичная деградация CDN для статики',
    service: 'CDN',
    priority: 'medium',
    status: 'monitoring',
    updatedAt: '2026-09-12T17:45:00.000Z',
    assignee: 'Дмитрий Соколов',
    description: 'Статика с CDN периодически отдаётся медленно или с ошибкой в отдельных регионах.',
  },
  {
    id: 'INC-1010',
    title: 'Ошибки записи метрик в систему мониторинга',
    service: 'Observability',
    priority: 'low',
    status: 'solved',
    updatedAt: '2026-09-12T08:05:00.000Z',
    assignee: 'Алексей Павлов',
    description: 'Часть сервисов не отправляла метрики в систему мониторинга из-за ошибки записи.',
  },
];
